abstract class ProductMangeStates {}
class CartInitialState extends ProductMangeStates{}
class CartSuccessAddState extends ProductMangeStates{}
class RemoveFromCartState extends ProductMangeStates{}
class FavouriteSuccessAddState extends ProductMangeStates{}
class RemoveFromFavouriteState extends ProductMangeStates{}
class CalculateTotalAmountState extends ProductMangeStates{}
class DecrementProductState extends ProductMangeStates{}
class IncrementProductState extends ProductMangeStates{}
